### ISSUE TITLE
JSHint chokes on node-sonos

### ISSUE THREAD

**Issue by ebaauw** [bencevans/node-sonos#207]
I'm using Atom with the linter-jshint package for my javascript development.

When opening sonos.js from node-sonos, JSHint gives up after 11% because of too many errors.  By the look of it, they're mostly warnings about missing semicolons.

**Comment by svrooij** [comment]
Ben chose [StandardJS](https://standardjs.com/) for linting (and mostly automatic fixing). They decided that we shouldn’t put `;` in JavaScript files since they are not needed by the interpreter.

It is just someone liking, I use StandardJS in all my node projects. And if you want you can even install it in Atom instead of JS hint [linter-js-standard](https://atom.io/packages/linter-js-standard)

**Comment by ebaauw** [comment]
Cool!  Something new to learn ;-)  Automatic code fixer sounds like something I'd want.

Related, albeit remotely: any tips on setting up automated testing?

**Comment by svrooij** [comment]
This project got some tests defined in [sonos.test.js](https://github.com/bencevans/node-sonos/blob/master/test/sonos.test.js) and they are automatically checked by [travis-CI](https://travis-ci.org] for every commit or pull-request.

You can also run the tests by typing `npm run test` in the root of the project.
Only linting the javascript can be done by running `standard` in the root or `standard --fix` if you want to have it automatically fix lint errors like forgotten spaces.
