### ISSUE TITLE
Problem with some events...

### ISSUE THREAD

**Issue by olivierjc** [bencevans/node-sonos#224]
Hi!
Some events are not sent. Especially, event 'AVTransport' (line 82 of eventParser.js).

**Comment by bencevans** [comment]
@olivierjc  please could you add the version you're using + maybe test the new version coming in soon.... https://github.com/bencevans/node-sonos/issues/206#issuecomment-358022097

**Comment by svrooij** [comment]
And also note that the current version in NPM doesn't have this event yet.
Check [here](https://github.com/bencevans/node-sonos/issues/218#issuecomment-358596840) if you want to use the async version right from your own library.

Otherwise could you try the following command, after checking out the latest version from the sonos-async branch.
```bash
node examples/events.js
```

**Comment by olivierjc** [comment]
I'm using sonos-async branch. Will test that this evening, thks.
There is also a pb on getQueue function, IP and Port in albumArtURI is undefined.

**Comment by svrooij** [comment]
The example returns the following here.
```text
AVTransport event {"TransportState":"PAUSED_PLAYBACK","CurrentPlayMode":"SHUFFLE","CurrentCrossfadeMode":"0","NumberOfTracks":"28","CurrentTrack":"15","CurrentSection":"0","CurrentTrackURI":"x-sonos-spotify:spotify%3atrack%3a04IwuF2IJkfEp3ROXLpMjb?sid=9&flags=8224&sn=7
```

Closing this issue for now, if you found that you still got this issue can you reopen this issue?

Ps. The `getQueue` now also returns the correct IP and port, fixed in [this commit](https://github.com/bencevans/node-sonos/commit/cb524619aff5b0306e6491900ed2f93abb9b8559)
