### ISSUE TITLE
TTS working ?

### ISSUE THREAD

**Issue by htilly** [bencevans/node-sonos#243]
Hi!

Trying to get TTS to work. Does it only support mp3 files?
Anyway to integrate in the same way as these guys are doing ?
https://github.com/jishi/node-sonos-http-api

Microsoft Cognitive Services (Bing Text to Speech API)
AWS Polly
Google (default)
macOS say command

BR
Tilly

**Comment by svrooij** [comment]
The problem is that sonos does accept .mp3 files in the url, but the urls from those companies don't end with `.mp3`.
You could however create some kind of php (or other language) redirect page that would accept `http://yourserver.com/tts/en_us/hello+world.mp3`  and them send them a 301 to one of those service.

Personally I don't get why you would create a http api for sonos, since it already got a http api (only a bit complicated). They do have the advantage that they are already hosting a webserver, so that might be where they do the redirection to those services.
