### ISSUE TITLE
Port to older Node Version

### ISSUE THREAD

**Issue by faxe1008** [bencevans/node-sonos#282]
Hi,

I wanted to know if you guys have a port to older versions of node specifically node version 6, since I am currently working on a aws project and for IoT only version 6 is supported at the moment.

**Comment by svrooij** [comment]
This library is migrated to be completely async. That made us choose not to support Node v6 anymore. (See here, for more info)[https://node.green/#ES2017-features-async-functions]

The old version is available [here](https://github.com/bencevans/node-sonos/tree/v0.x) from before the async transition. This might not have all the features since we changed a lot with the conversion to being async.
