### ISSUE TITLE
playNotification does not resume

### ISSUE THREAD

**Issue by egs2003** [bencevans/node-sonos#389]
If I play a spotify stream and play a notification, spotify does not resume

**Comment by svrooij** [comment]
I noticed this sometime too.... Anyone got a solution for this?

Because I'm affraid to use the `It works on my network`-card.

**Comment by svrooij** [comment]
@egs2003 could you please test the *playNotification* sample with this command. `SONOS_HOST=x.x.x.x node examples\playNotification.js`.
What do you mean with a spotify stream?

@CRRE3D the specified code is from some other library and is unrelated to the original question.

In the mean time I'm adding some tests to the library that could be tested.


Both requests could be linked to the event listener not working because of a firewall of some kind. The playNotification method uses the event listener to receive a notification when the playing state changes. The event listener is run on port *4000* by default and could be changed with the `SONOS_LISTENER_PORT` environment listener.

This issue will be closed for now, please re-open if the above doesn't solve your problem.
