### ISSUE TITLE
Recursive XML parsing?

### ISSUE THREAD

**Issue by monsur** [bencevans/node-sonos#66]
Some Sonos responses contain nested XML, or XML in attributes. For example, in the zoneTopologySubscription.js example, the LastChange json property is actually a string of XML. It would be nice of node-sonos could parse all levels of XML, so that the developer doesn't have to write additional XML parsing code.

**Comment by bencevans** [comment]
Agreed. This would be good.

**Comment by svrooij** [comment]
There will be a parseXml in the sonos class soon, that way the code to read the xml would be minimal.
Parsing all the properties is not easy, but once it is implemented you could maybe give it a go with a pull-request

**Comment by svrooij** [comment]
Recursive parsing xml is hard, because not all properties are xml, but in the async version we got an asynchronous `Helpers.ParseXml` [here](https://github.com/bencevans/node-sonos/blob/5ec624d7d63a9ec164fd2634ca0e9e20b49365b3/lib/helpers.js#L182) That can be used for parsing returned xml.

Hoping that this will solve your problem with xml returned by the sonos api.
